-d /home/muheet-ghani/fpga_project/impl/gwsynthesis/fpga_project.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/muheet-ghani/fpga_project/src/fpga_project.cst
-cfg /home/muheet-ghani/fpga_project/impl/pnr/device.cfg
-sdc /home/muheet-ghani/fpga_project/src/fpga_project.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
